#!/usr/local/bin/python3
import json
import feedparser

with open('public/backup.json') as fin:
    posts = json.load(fin)
    indices = set()
    for post in posts:
        indices.add(post['id'])
    print('Stored:', len(indices), 'post(s)')

    print('Updating feed…')
    feed = feedparser.parse('http://blog.yitianshijie.net/feed')
    for entry in feed.entries:
        if entry.id not in indices:
            print('Added:', entry.title, entry.link)
            indices.add(entry.id)
            posts.append({
                "title": entry.title,
                "author": entry.author,
                "id": entry.id,
                "slug": entry.link.replace('https://blog.yitianshijie.net/', ''),
                "description": entry.description,
                "content": entry.content[0].value
            })

with open('public/backup.json', 'w') as fout:
    fout.write(json.dumps(posts, ensure_ascii=False))

